Cis_MRBEE_IPOD_SuSiE=function(by,bX,byse,bXse,LD,Rxy,cluster.index=c(1:length(by)),Lvec=c(1:min(10,nrow(bX))),pip.thres=0.2,tauvec=seq(3,50,by=2),max.iter=100,max.eps=0.001,susie.iter=100,ebic.theta=1,ebic.gamma=2,reliability.thres=0.8,rho=2,maxdiff=1.5,theta.ini=F,gamma.ini=F,estimate_residual_variance=T,residual_variance=1,ridge=ridge,block.rho=0,robust.sandwith){
########################### Basic information #######################
by=by/byse
byseinv=1/byse
bX=bX*byseinv
bXse=bXse*byseinv
byse1=byse
byse=byse/byse
m=nrow(bX)
p=ncol(bX)
LD=as.matrix(LD)
Theta=matrixInverse(LD)
TC=chol(Theta)
bXinv=matrixMultiply(Theta,bX)
tilde.y=as.vector(TC%*%by)
tilde.X=matrixMultiply(TC,bX)
Bt=t(bXinv)
BtB=matrixMultiply(Bt,bX)
BtB=(t(BtB)+BtB)/2
ridge=ridge*m
Thetarho=solve(LD+rho*diag(m))
r=reliability.adj(bX,bXse,Theta=Theta,thres=reliability.thres)
r=c(r,1)
Rxy=t(t(Rxy)*r)*r
RxyList=IVweight(byse,bXse,Rxy)
Rxyall=biasterm(RxyList=RxyList,c(1:m))
############################ Initial Estimate #######################
if(theta.ini[1]==F){
if(length(tilde.y)<2000){
RC=matrixMultiply(TC,LD)
fit0=varbvs(X=RC,Z=tilde.X,y=tilde.y,verbose=F,maxiter=100)
gamma.ini=gamma.ini1=fit0$beta*(fit0$pip>0.5)
theta.ini=theta.ini1=fit0$beta.cov[-1]
}else{
fit0=MRBEE_IMRP(by=by,bX=bX,byse=byse,bXse=bXse,Rxy=Rxy,var.est="variance",FDR="Sidak",pv.thres=0.01)
gamma.ini=gamma.ini1=fit0$gamma
theta.ini=theta.ini1=fit0$theta
}
}else{
gamma.ini=gamma.ini1=gamma.ini/byse1
theta.ini=theta.ini1=theta.ini
}
############################## Tuning Parameter ######################
w=length(tauvec)
q=length(Lvec)
Btheta=array(0,c(p,w,q))
Bgamma=array(0,c(m,w,q))
Bbic=matrix(0,w,q)
for(v in length(Lvec):1){
fit.theta=NULL
for(j in length(tauvec):1){
theta=theta.ini
gamma=gamma.ini
gamma1=gamma
delta=gamma1*0
error=1
iter=1
while(error>max.eps&iter<max.iter){
theta1=theta
indvalid=which(gamma1==0)
if(length(indvalid)==m){
Rxysum=Rxyall
}else{
Rxysum=Rxyall-biasterm(RxyList=RxyList,setdiff(1:m,indvalid))
}
res.theta=by-matrixVectorMultiply(LD,gamma)
XtX=BtB
Xty=matrixVectorMultiply(Bt,res.theta)
yty=sum(res.theta*matrixVectorMultiply(Theta,res.theta))
fit.theta=susie_suff_stat(XtX=XtX,Xty=Xty,yty=yty,n=m,L=Lvec[v],residual_variance=residual_variance,estimate_residual_variance=estimate_residual_variance,estimate_prior_method="EM",intercept=F,max_iter=susie.iter,standardize=T,s_init=fit.theta)
theta=coef.susie(fit.theta)[-1]*(fit.theta$pip>pip.thres)
indtheta=which(theta!=0)
if(length(indtheta)==1){
xtx=XtX[indtheta,indtheta]-Rxysum[indtheta,indtheta]+ridge
xty=Xty[indtheta]-Rxysum[indtheta,p+1]
theta[indtheta]=xty/xtx
}
if(length(indtheta)>1){
XtX=XtX[indtheta,indtheta]-Rxysum[indtheta,indtheta]+ridge*diag(length(indtheta))
Xty=Xty[indtheta]-Rxysum[indtheta,p+1]
theta[indtheta]=c(solve(XtX)%*%Xty)
}
if((norm(theta,"2")/norm(theta.ini1,"2"))>maxdiff){
theta=theta/norm(theta,"2")*maxdiff*norm(theta.ini1,"2")
}
gamma=as.vector(Thetarho%*%(by-matrixVectorMultiply(bX,theta)-delta+rho*gamma1))
gamma1=mcp(gamma+delta/rho,tauvec[j]/rho)
delta=delta+rho*(gamma-gamma1)
iter=iter+1
if(iter>3){
error=max(abs(theta-theta1))
}
}
Btheta[,j,v]=theta
Bgamma[,j,v]=gamma1
df1=sum(gamma1!=0)
df2=min(Lvec[v],sum(theta!=0))
res=by-matrixVectorMultiply(bX,theta)-matrixVectorMultiply(LD,gamma)
rss=sum(res*(Theta%*%res))/(m-df1-df2)
Bbic[j,v]=log(rss)*m+(log(m)+ebic.gamma*log(m))*df1+df2*(log(m)+ebic.theta*log(p))
}
}
Bbic=Bbic/m
jstar=bimin(Bbic)[1]
vstar=bimin(Bbic)[2]
theta.ini=Btheta[,jstar,vstar]
gamma.ini=Bgamma[,jstar,vstar]
indvalid=which(gamma.ini==0)
theta=theta.ini
gamma=gamma1=gamma.ini
delta=0*gamma
error=1
iter=1
fit.theta=NULL
while(error>max.eps&iter<max.iter){
theta1=theta
indvalid=which(gamma1==0)
if(length(indvalid)==m){
Rxysum=Rxyall
}else{
Rxysum=Rxyall-biasterm(RxyList=RxyList,setdiff(1:m,indvalid))
}
res.theta=by-matrixVectorMultiply(LD,gamma)
XtX=BtB
Xty=matrixVectorMultiply(Bt,res.theta)
yty=sum(res.theta*(Theta%*%res.theta))
fit.theta=susie_suff_stat(XtX=XtX,Xty=Xty,yty=yty,n=m,L=Lvec[vstar],residual_variance=residual_variance,estimate_prior_method="EM",intercept=F,estimate_residual_variance=estimate_residual_variance,max_iter=susie.iter*10,standardize=T,s_init=fit.theta)
theta=coef.susie(fit.theta)[-1]*(fit.theta$pip>pip.thres)
indtheta=which(theta!=0)
if(length(indtheta)==1){
xtx=XtX[indtheta,indtheta]-Rxysum[indtheta,indtheta]+ridge
xty=Xty[indtheta]-Rxysum[indtheta,p+1]
theta[indtheta]=xty/xtx
}
if(length(indtheta)>1){
XtX=XtX[indtheta,indtheta]-Rxysum[indtheta,indtheta]+ridge*diag(length(indtheta))
Xty=Xty[indtheta]-Rxysum[indtheta,p+1]
theta[indtheta]=c(solve(XtX)%*%Xty)
}
if((norm(theta,"2")/norm(theta.ini1,"2"))>maxdiff){
theta=theta/norm(theta,"2")*maxdiff*norm(theta.ini1,"2")
}
gamma=matrixVectorMultiply(Thetarho,by-matrixVectorMultiply(bX,theta)-delta+rho*gamma1)
gamma1=mcp(gamma+delta/rho,tauvec[jstar]/rho)
delta=delta+rho*(gamma-gamma1)
iter=iter+1
if(iter>3){
error=max(abs(theta-theta1))
}
}
############################### inference #########################
gamma=gamma1
theta=theta
names(theta)=colnames(bX)
names(gamma)=rownames(bX)
indtheta=which(theta!=0)
indgamma=which(gamma1!=0)
indvalid=which(gamma1==0)
res=by-matrixVectorMultiply(bX,theta)-matrixVectorMultiply(LD,gamma)
adjf=m/(length(indvalid)-length(indtheta))

if(length(indtheta)>0){
bZ=cbind(bX[,indtheta],as.matrix(LD[,indgamma]))
TCbZ=TC%*%bZ
Hinv=matrixListProduct(list(t(bZ),Theta,bZ))
Hinv[1:length(indtheta),1:length(indtheta)]=Hinv[1:length(indtheta),1:length(indtheta)]-Rxysum[indtheta,indtheta]+ridge*diag(length(indtheta))
Hinv=solve(as.matrix(Hinv))
D=TCbZ%*%(Hinv%*%t(TCbZ))
D=as.matrix(D)
D=rep(1,m)-diag(D)
D[which(D<0.5)]=0.5
S=diag(res^2/D^2)
V=as.matrix(t(bZ)%*%Theta%*%S%*%Theta%*%bZ)
IV=rep(0,nrow(V));IV[1:length(indtheta)]=1
V=V+ridge*diag(IV)
COV=as.matrix(Hinv%*%V%*%Hinv)*adjf
theta.cov=diag(p)*0
theta.cov[indtheta,indtheta]=COV[1:length(indtheta),1:length(indtheta)]
theta.se=sqrt(diag(theta.cov))
}

if(length(indtheta)==0){
theta.cov=diag(p)*0
theta.se=rep(0,p)
}

A=list()
A$theta=theta
A$gamma=gamma*byse1
A$theta.se=theta.se
A$theta.cov=theta.cov
A$theta.pip=fit.theta$pip
A$Bic=Bbic
A$reliability.adjust=r
A$susie.theta=fit.theta
A$theta.pratt=getPratt(bX=bX,by=by,bXse=bXse,byse=byse,Theta=Theta,theta=theta,Rxy=Rxy)
A$gamma.pratt=pleiotropyPratt(by=by,pleiotropy=gamma,Theta=Theta,LD=LD)
return(A)
}
