MRBEE_Mixture_SuSiE=function(by,bX,byse,bXse,LD,Rxy,cluster.index=c(1:length(by)),main.cluster.thres=0.48,min.cluster.size=5,Lvec=c(1:min(5,ncol(bX))),pip.thres=0.2,ebic.theta=1,ebic.gamma=1,reliability.thres=0.8,sampling.time=100,robust.se=T,max.iter=30,max.eps=5e-4,sampling.iter=5,tau=tau,step.size=0.8,ebic.en=1){
########################### Basic information #######################
by=by/byse
byseinv=1/byse
bX=bX*byseinv
bXse=bXse*byseinv
byse1=byse
byse=byse/byse
m=nrow(bX)
p=ncol(bX)
if(LD[1]!="identity"){
LD=Matrix(LD,sparse=T)
Theta=solve(LD)
TC=chol(Theta)
}else{
LD=Theta=TC=Matrix(diag(m),sparse=T)
}
tilde.y=as.vector(TC%*%by)
tilde.X=as.matrix(TC%*%bX)
tilde.R=as.matrix(TC%*%LD)
inv.y=as.vector(Theta%*%by)
inv.X=as.matrix(Theta%*%bX)
r=reliability.adj(bX,bXse,Theta=Theta,thres=reliability.thres)
r=c(r,1)
Rxy=t(t(Rxy)*r)*r
RxyList=IVweight(byse,bXse,Rxy)
Rxyall=biasterm(RxyList=RxyList,c(1:m))
############################ Initial Estimate #######################
fit.init=fit.mixture=regmixEM(y=tilde.y,x=tilde.X,k=2,addintercept=F,maxit=300,epsilon=max.eps)
max.cluster=ifelse(sum(fit.init$posterior[,1]>main.cluster.thres)>(m/2),1,2)
cluster.ini.1=which(fit.init$posterior[,max.cluster]>main.cluster.thres)
cluster.ini.2=setdiff(1:m,cluster.ini.1)
theta.ini.1=theta.ini.11=fit.init$beta[,max.cluster]
theta.ini.2=theta.ini.22=fit.init$beta[,setdiff(1:2,max.cluster)]
fit.susie.init1=susie(X=tilde.X[cluster.ini.1,],y=tilde.y[cluster.ini.1],L=5,intercept=F)
fit.susie.init2=susie(X=tilde.X[cluster.ini.2,],y=tilde.y[cluster.ini.2],L=5,intercept=F)
theta.ini.1=coef.susie(fit.susie.init1)[-1]*(fit.susie.init1$pip>0.1)
theta.ini.2=coef.susie(fit.susie.init2)[-1]*(fit.susie.init2$pip>0.1)
sigma.ini.1=sum((tilde.y[cluster.ini.1]-tilde.X[cluster.ini.1,]%*%theta.ini.1)^2)/(length(cluster.ini.1)-sum(theta.ini.1!=0))
sigma.ini.2=sum((tilde.y[cluster.ini.2]-tilde.X[cluster.ini.2,]%*%theta.ini.2)^2)/(length(cluster.ini.2)-sum(theta.ini.2!=0))
sigma.ini.2=max(0.1,sigma.ini.2)
sigma.ini.1=max(0.1,sigma.ini.1)
Voting.ini=cluster_voting(by=tilde.y,bX=tilde.X,cluster.index=cluster.index,theta1=theta.ini.1,theta2=theta.ini.2,sigma1=sigma.ini.1,sigma2=sigma.ini.2,main.cluster.thres=main.cluster.thres)
cluster.ini.2=which(Voting.ini$Cluster[,2]==1)
cluster.ini.1=which(Voting.ini$Cluster[,1]==1)
cluster.ratio.ini=c(length(cluster.ini.1),length(cluster.ini.2))/m
############################## Tuning Parameter ######################
q=length(Lvec)
Btheta1=array(0,c(p,q,q))
Btheta2=array(0,c(p,q,q))
Bbic=matrix(1e6,q,q)

for(v in 1:length(Lvec)){
fit.susie1=fit.susie2=NULL
for(j in 1:v){
theta1=theta.ini.1
theta2=theta.ini.2
cluster1=cluster.ini.1
cluster2=cluster.ini.2
cluster.ratio=cluster.ratio.ini
iter=0
error=1
gamma=0*by
fit.susie2=NULL
while(iter<max.iter&error>max.eps){
theta11=theta1
theta22=theta2
indvalid=which(gamma==0)
valid1=intersect(indvalid,cluster1)
valid2=intersect(indvalid,cluster2)
Rxysum1=biasterm(RxyList=RxyList,valid1)
gamma.y=tilde.y-matrixVectorMultiply(tilde.R,gamma)
XtX1=matrixMultiply(t(tilde.X[cluster1,]),tilde.X[cluster1,])
XtX1=t(XtX1)/2+XtX1/2
Xty1=matrixVectorMultiply(t(tilde.X[cluster1,]),gamma.y[cluster1])
yty1=sum(gamma.y[cluster1]^2)
fit.susie1=susie_suff_stat(XtX=XtX1,Xty=Xty1,yty=yty1,n=length(cluster1),L=Lvec[v],max_iter=300,intercept=F,estimate_prior_method="EM",s_init=fit.susie1)
theta1=coef.susie(fit.susie1)[-1]*(fit.susie1$pip>(pip.thres*max(1/5,cluster.ratio[1])))
if(length(cluster2)>min.cluster.size){
Rxysum2=biasterm(RxyList=RxyList,valid2)
XtX2=matrixMultiply(t(tilde.X[cluster2,]),tilde.X[cluster2,])
XtX2=t(XtX2)/2+XtX2/2
Xty2=matrixVectorMultiply(t(tilde.X[cluster2,]),gamma.y[cluster2])
yty2=sum(gamma.y[cluster2]^2)
fit.susie2=susie_suff_stat(XtX=XtX2,Xty=Xty2,yty=yty2,n=length(cluster2),L=Lvec[j],max_iter=300,intercept=F,estimate_prior_method="EM",s_init=fit.susie2)
theta2=coef.susie(fit.susie2)[-1]*(fit.susie2$pip>(pip.thres*min(1/5,cluster.ratio[2])))
}else{
theta2=theta1*0
cluster2=sample(m,min.cluster.size)
}
indtheta1=which(theta1!=0)
if(length(indtheta1)==1){
xtx1=XtX1[indtheta1,indtheta1]-Rxysum1[indtheta1,indtheta1]
xty1=Xty1[indtheta1]-Rxysum1[indtheta1,p+1]
theta1[indtheta1]=xty1/xtx1
}
if(length(indtheta1)>1){
XtX1=XtX1[indtheta1,indtheta1]-Rxysum1[indtheta1,indtheta1]
Xty1=Xty1[indtheta1]-Rxysum1[indtheta1,p+1]
theta1[indtheta1]=c(solve(XtX1)%*%Xty1)
}
indtheta2=which(theta2!=0)
if(length(indtheta2)==1){
xtx2=XtX2[indtheta2,indtheta2]-Rxysum2[indtheta2,indtheta2]
xty2=Xty2[indtheta2]-Rxysum2[indtheta2,p+1]
theta2[indtheta2]=xty2/xtx2
}
if(length(indtheta2)>1){
XtX2=XtX2[indtheta2,indtheta2]-Rxysum2[indtheta2,indtheta2]
Xty2=Xty2[indtheta2]-Rxysum2[indtheta2,p+1]
theta2[indtheta2]=c(solve(XtX2)%*%Xty2)
}
res.theta=as.vector(tilde.y-tilde.R%*%gamma)
sigma1=sum((res.theta[cluster1]-tilde.X[cluster1,]%*%theta1)^2)/(length(cluster1)-sum(theta1!=0))
sigma2=sum((res.theta[cluster2]-tilde.X[cluster2,]%*%theta2)^2)/(length(cluster2)-sum(theta2!=0))
sigma2=max(0.1,sigma2)
sigma1=max(0.1,sigma1)
Voting=cluster_voting(by=res.theta,bX=tilde.X,cluster.index=cluster.index,theta1=theta1,theta2=theta2,sigma1=sigma1,sigma2=sigma2,main.cluster.thres=main.cluster.thres)
cluster2=which(Voting$Cluster[,2]==1)
cluster1=which(Voting$Cluster[,1]==1)
grad=tilde.y
grad[cluster1]=tilde.y[cluster1]-tilde.X[cluster1,]%*%theta1
grad[cluster2]=tilde.y[cluster2]-tilde.X[cluster2,]%*%theta2
grad=matrixVectorMultiply(t(tilde.R),-grad+matrixVectorMultiply(tilde.R,gamma))
gamma=gamma-grad*step.size
gamma=mcp(gamma,tau)
iter=iter+1
if(iter>3){
error=min(norm(theta1-theta11,"2"),norm(theta2-theta22,"2"))
}
}
Btheta1[,v,j]=theta1
Btheta2[,v,j]=theta2
df1=min(sum(theta1!=0),Lvec[v])
df2=min(sum(theta2!=0),Lvec[j])
Bbic[v,j]=MRFit(by=as.vector(tilde.y-tilde.R%*%gamma),bX=tilde.X,theta1=theta1,theta2=theta2,cluster1=cluster1,cluster2=cluster2,df1=df1,df2=df2,ebic.en=ebic.en)+(df2+df1)*(log(p*2)*ebic.theta+log(m))+log(m)*(1+ebic.gamma)*sum(gamma!=0)
}
}
Bbic=Bbic/m
######################## Final Estimate #################################
vstar=bimin(Bbic)[1]
jstar=bimin(Bbic)[2]
theta1=Btheta1[,vstar,jstar]
theta2=Btheta2[,vstar,jstar]
cluster.ratio=cluster.ratio.ini
cluster1=cluster.ini.1
cluster2=cluster.ini.2
iter=0
error=1
theta11=theta1*0
theta22=theta2*0
gamma=0*by
fit.susie1=fit.susie2=NULL
while(iter<(max.iter*2)&error>max.eps){
theta11=theta1
theta22=theta2
indvalid=which(gamma==0)
valid1=intersect(indvalid,cluster1)
valid2=intersect(indvalid,cluster2)
Rxysum1=biasterm(RxyList=RxyList,valid1)
gamma.y=tilde.y-matrixVectorMultiply(tilde.R,gamma)
XtX1=matrixMultiply(t(tilde.X[cluster1,]),tilde.X[cluster1,])
XtX1=t(XtX1)/2+XtX1/2
Xty1=matrixVectorMultiply(t(tilde.X[cluster1,]),tilde.y[cluster1])
yty1=sum(tilde.y[cluster1]^2)
fit.susie1=susie_suff_stat(XtX=XtX1,Xty=Xty1,yty=yty1,n=length(cluster1),L=Lvec[vstar],max_iter=300,intercept=F,estimate_prior_method="EM",s_init=fit.susie1)
theta1=coef.susie(fit.susie1)[-1]*(fit.susie1$pip>(pip.thres*max(1/5,cluster.ratio[1])))
if(length(cluster2)>min.cluster.size){
Rxysum2=biasterm(RxyList=RxyList,valid2)
XtX2=matrixMultiply(t(tilde.X[cluster2,]),tilde.X[cluster2,])
XtX2=t(XtX2)/2+XtX2/2
Xty2=matrixVectorMultiply(t(tilde.X[cluster2,]),tilde.y[cluster2])
yty2=sum(tilde.y[cluster2]^2)
fit.susie2=susie_suff_stat(XtX=XtX2,Xty=Xty2,yty=yty2,n=length(cluster2),L=Lvec[jstar],max_iter=300,intercept=F,estimate_prior_method="EM",s_init=fit.susie2)
theta2=coef.susie(fit.susie2)[-1]*(fit.susie2$pip>(pip.thres*min(1/5,cluster.ratio[2])))
}else{
theta2=theta1*0
cluster2=sample(m,min.cluster.size)
}
indtheta1=which(theta1!=0)
if(length(indtheta1)==1){
xtx1=XtX1[indtheta1,indtheta1]-Rxysum1[indtheta1,indtheta1]
xty1=Xty1[indtheta1]-Rxysum1[indtheta1,p+1]
theta1[indtheta1]=xty1/xtx1
}
if(length(indtheta1)>1){
XtX1=XtX1[indtheta1,indtheta1]-Rxysum1[indtheta1,indtheta1]
Xty1=Xty1[indtheta1]-Rxysum1[indtheta1,p+1]
theta1[indtheta1]=c(solve(XtX1)%*%Xty1)
}
indtheta2=which(theta2!=0)
if(length(indtheta2)==1){
xtx2=XtX2[indtheta2,indtheta2]-Rxysum2[indtheta2,indtheta2]
xty2=Xty2[indtheta2]-Rxysum2[indtheta2,p+1]
theta2[indtheta2]=xty2/xtx2
}
if(length(indtheta2)>1){
XtX2=XtX2[indtheta2,indtheta2]-Rxysum2[indtheta2,indtheta2]
Xty2=Xty2[indtheta2]-Rxysum2[indtheta2,p+1]
theta2[indtheta2]=c(solve(XtX2)%*%Xty2)
}
res.theta=as.vector(tilde.y-tilde.R%*%gamma)
sigma1=sum((res.theta[cluster1]-tilde.X[cluster1,]%*%theta1)^2)/(length(cluster1)-sum(theta1!=0))
sigma2=sum((res.theta[cluster2]-tilde.X[cluster2,]%*%theta2)^2)/(length(cluster2)-sum(theta2!=0))
sigma2=max(0.1,sigma2)
sigma1=max(0.1,sigma1)
Voting=cluster_voting(by=res.theta,bX=tilde.X,cluster.index=cluster.index,theta1=theta1,theta2=theta2,sigma1=sigma1,sigma2=sigma2,main.cluster.thres=main.cluster.thres)
cluster2=which(Voting$Cluster[,2]==1)
cluster1=which(Voting$Cluster[,1]==1)
grad=tilde.y
grad[cluster1]=tilde.y[cluster1]-tilde.X[cluster1,]%*%theta1
grad[cluster2]=tilde.y[cluster2]-tilde.X[cluster2,]%*%theta2
grad=matrixVectorMultiply(t(tilde.R),-grad+matrixVectorMultiply(tilde.R,gamma))
gamma=gamma-grad*step.size
gamma=mcp(gamma,tau)
iter=iter+1
if(iter>3){
error=min(norm(theta1-theta11,"2"),norm(theta2-theta22,"2"))
}
}
############################### inference #########################
cat("Bootstrapping process:\n")
pb <- txtProgressBar(min = 0, max = sampling.time, style = 3)
names(theta1)=names(theta2)=colnames(bX)
ThetaList1=ThetaList2=matrix(0,sampling.time,p)
colnames(ThetaList1)=colnames(ThetaList2)=colnames(bX)
j=1
while(j<=sampling.time){
indicator <- FALSE
setTxtProgressBar(pb, j)
tryCatch({
cluster.sampling <- sample(1:max(cluster.index), 0.5*max(cluster.index), replace = F)
indj=which(cluster.index%in%cluster.sampling)
indj=sort(indj)
tilde.yj=tilde.y[indj]
tilde.Xj=tilde.X[indj,]
tilde.Rj=tilde.R[indj,indj]
theta1j=theta1*runif(1,0.95,1.05)*0.95
theta2j=theta2*runif(1,0.95,1.05)*0.95
cluster1j=which(indj%in%cluster1)
cluster2j=which(indj%in%cluster2)
gammaj=tilde.yj*0
for(iterj in 1:sampling.iter){
indvalidj=which(gammaj==0)
valid1j=intersect(indvalidj,cluster1j)
valid2j=intersect(indvalidj,cluster2j)
gamma.yj=tilde.yj-matrixVectorMultiply(tilde.Rj,gammaj)
Rxysum1j=biasterm(RxyList=RxyList,indj[valid1j])
XtX1j=matrixMultiply(t(tilde.Xj[cluster1j,]),tilde.Xj[cluster1j,])
XtX1j=t(XtX1j)/2+XtX1j/2
Xty1j=matrixVectorMultiply(t(tilde.Xj[cluster1j,]),gamma.yj[cluster1j])
yty1j=sum(gamma.yj[cluster1j]^2)
fit.susie1j=susie_suff_stat(XtX=XtX1j,Xty=Xty1j,yty=yty1j,n=length(cluster1j),L=Lvec[vstar],max_iter=300,s_init=fit.susie1,intercept=F,estimate_prior_method="EM")
theta1j=coef.susie(fit.susie1j)[-1]*(fit.susie1j$pip>(pip.thres*max(1/5,cluster.ratio[1])))
if(length(cluster2j)>(min.cluster.size/2)){
Rxysum2j=biasterm(RxyList=RxyList,indj[valid2j])
XtX2j=matrixMultiply(t(tilde.Xj[cluster2j,]),tilde.Xj[cluster2j,])
XtX2j=XtX2j/2+t(XtX2j)/2
Xty2j=matrixVectorMultiply(t(tilde.Xj[cluster2j,]),gamma.yj[cluster2j])
yty2j=sum(gamma.yj[cluster2j]^2)
fit.susie2j=susie_suff_stat(XtX=XtX2j,Xty=Xty2j,yty=yty2j,n=length(cluster2j),L=Lvec[jstar],max_iter=300,s_init=fit.susie2,intercept=F,estimate_prior_method="EM")
theta2j=coef.susie(fit.susie2j)[-1]*(fit.susie2j$pip>(pip.thres*min(1/5,cluster.ratio[2])))
}else{
theta2j=theta1j*0
cluster2j=sample(length(indj),max(round(min.cluster.size/2),1))
}
indtheta1j=which(theta1j!=0)
if(length(indtheta1j)==1){
xtx1j=XtX1j[indtheta1j,indtheta1j]-Rxysum1j[indtheta1j,indtheta1j]
xty1j=Xty1j[indtheta1j]-Rxysum1j[indtheta1j,p+1]
theta1j[indtheta1j]=xty1j/xtx1j
}
if(length(indtheta1j)>1){
XtX1j=XtX1j[indtheta1j,indtheta1j]-Rxysum1j[indtheta1j,indtheta1j]
Xty1j=Xty1j[indtheta1j]-Rxysum1j[indtheta1j,p+1]
theta1j[indtheta1j]=c(solve(XtX1j)%*%Xty1j)
}
indtheta2j=which(theta2j!=0)
if(length(indtheta2j)==1){
xtx2j=XtX2j[indtheta2j,indtheta2j]-Rxysum2j[indtheta2j,indtheta2j]
xty2j=Xty2j[indtheta2j]-Rxysum2j[indtheta2j,p+1]
theta2j[indtheta2j]=xty2j/xtx2j
}
if(length(indtheta2j)>1){
XtX2j=XtX2j[indtheta2j,indtheta2j]-Rxysum2j[indtheta2j,indtheta2j]
Xty2j=Xty2j[indtheta2j]-Rxysum2j[indtheta2j,p+1]
theta2j[indtheta2j]=c(solve(XtX2j)%*%Xty2j)
}
res.thetaj=as.vector(tilde.yj-tilde.Rj%*%gammaj)
sigma1j=sum((res.thetaj[cluster1j]-tilde.Xj[cluster1j,]%*%theta1j)^2)/(length(cluster1j)-sum(theta1j!=0))
sigma2j=sum((res.thetaj[cluster2j]-tilde.Xj[cluster2j,]%*%theta2j)^2)/(length(cluster2j)-sum(theta2j!=0))
sigma2j=max(0.1,sigma2j)
sigma1j=max(0.1,sigma1j)
Votingj=cluster_voting(by=res.thetaj,bX=tilde.Xj,cluster.index=cluster.index[indj],theta1=theta1j,theta2=theta2j,sigma1=sigma1j,sigma2=sigma2j,main.cluster.thres=main.cluster.thres)
cluster2j=which(Votingj$Cluster[,2]==1)
cluster1j=which(Votingj$Cluster[,1]==1)
gradj=tilde.yj
gradj[cluster1j]=tilde.yj[cluster1j]-tilde.Xj[cluster1j,]%*%theta1j
gradj[cluster2j]=tilde.yj[cluster2j]-tilde.Xj[cluster2j,]%*%theta2j
grad=matrixVectorMultiply(t(tilde.Rj),-gradj+matrixVectorMultiply(tilde.Rj,gammaj))
gammaj=gammaj-gradj*step.size
gammaj=mcp(gammaj,tau)
}
ThetaVecj=cbind(theta1j,theta2j)
ThetaNormj=colMeans((ThetaVecj-cbind(theta1,theta1))^2)
theta1j=ThetaVecj[,which.min(ThetaNormj)]
theta2j=ThetaVecj[,which.max(ThetaNormj)]

ThetaList1[j, ] <- theta1j
ThetaList2[j, ] <- theta2j
j=j+1
}, error = function(e) {
# Error handling block
cat("Error occurred: ", e$message, "\n")
indicator <<- TRUE  # Set indicator to TRUE if an error occurs
j <<- j - 1  # Decrement the iteration counter to retry
})
if (indicator) {
next  # Retry the current iteration
}
}
close(pb)
indtheta1=which(theta1!=0)
indtheta2=which(theta2!=0)
theta.se1=colSD(ThetaList1)
theta.cov1=cov(ThetaList1)
theta.se2=colSD(ThetaList2)
theta.cov2=cov(ThetaList2)
if(robust.se==T){
theta.se1=colSDMAD(ThetaList1)
theta.cov1=covmad(ThetaList1)
theta.se2=colSDMAD(ThetaList2)
theta.cov2=covmad(ThetaList2)
}
colnames(theta.cov2)=rownames(theta.cov2)=names(theta.se2)=colnames(bX)
colnames(theta.cov1)=rownames(theta.cov1)=names(theta.se1)=colnames(bX)

A=list()
A$theta1=theta1
A$theta2=theta2
A$theta.se1=theta.se1
A$theta.cov1=theta.cov1
A$theta.se2=theta.se2
A$theta.cov2=theta.cov2
A$Bic=Bbic
A$reliability.adjust=r
A$thetalist1=ThetaList1
A$thetalist2=ThetaList2
A$Voting=Voting
A$theta.pip1=colMeans(ThetaList1!=0)
A$theta.pip2=colMeans(ThetaList2!=0)
A$theta.pratt1=getPratt(bX=bX[cluster1,],by=by[cluster1],bXse=bXse[cluster1,],byse=byse[cluster1],Theta=solve(LD[cluster1,cluster1]),theta=theta1,Rxy=Rxy)
A$theta.pratt2=getPratt(bX=bX[cluster2,],by=by[cluster2],bXse=bXse[cluster2,],byse=byse[cluster2],Theta=solve(LD[cluster2,cluster2]),theta=theta2,Rxy=Rxy)
A$susie.theta1=fit.susie1
A$susie.theta2=fit.susie2
A$gamma=gamma
A$IsIPOD=F
return(A)
}

