MRBEE_Mixture_SuSiE_Independent=function(by,bX,byse,bXse,Rxy,main.cluster.thres=0.4,min.cluster.size=5,Lvec=c(1:min(5,ncol(bX))),pip.thres=0.2,reliability.thres=0.8,sampling.time=100,ebic.theta=ebic.theta,robust.se=T){
########################### Basic information #######################
by=by/byse
byseinv=1/byse
bX=bX*byseinv
bXse=bXse*byseinv
byse1=byse
byse=byse/byse
m=nrow(bX)
p=ncol(bX)
r=reliability.adj(bX,bXse,Theta="identity",thres=reliability.thres)
r=c(r,1)
Rxy=t(t(Rxy)*r)*r
RxyList=IVweight(byse,bXse,Rxy)
Rxyall=biasterm(RxyList=RxyList,c(1:m))
cluster.index=c(1:m)
############################ Initial Estimate #######################
fit.init=fit.mixture=regmixEM(y=by,x=bX,k=2,addintercept=F)
max.cluster=ifelse(sum(fit.init$posterior[,1]>main.cluster.thres)>(m/2),1,2)
cluster.ini.1=which(fit.init$posterior[,max.cluster]>main.cluster.thres)
cluster.ini.2=setdiff(1:m,cluster.ini.1)
########################### Check if applied mixture model #######################
if(length(cluster.ini.2)>=min.cluster.size){
theta.ini.1=theta.ini.11=fit.init$beta[,max.cluster]
theta.ini.2=theta.ini.22=fit.init$beta[,setdiff(1:2,max.cluster)]
fit.susie.init1=susie(X=bX[cluster.ini.1,],y=by[cluster.ini.1],L=5,intercept=F)
fit.susie.init2=susie(X=bX[cluster.ini.2,],y=by[cluster.ini.2],L=5,intercept=F)
theta.ini.1=coef.susie(fit.susie.init1)[-1]*(fit.susie.init1$pip>0.1)
theta.ini.2=coef.susie(fit.susie.init2)[-1]*(fit.susie.init2$pip>0.1)
Rxysum2=biasterm(RxyList=RxyList,cluster.ini.2)
Rxysum1=biasterm(RxyList=RxyList,cluster.ini.1)
############################## Tuning Parameter ######################
q=length(Lvec)
Btheta1=array(0,c(p,q))
Btheta2=array(0,c(p,q))
Bbic=c(1:q)
for(v in length(Lvec):1){
error=1
iter=1
theta1=theta.ini.1
theta2=theta.ini.2
cluster.1=cluster.ini.1
cluster.2=cluster.ini.2
cluster.ratio=c(length(cluster.1),length(cluster.2))/m
Rxysum1=biasterm(RxyList=RxyList,cluster.1)
XtX1=matrixMultiply(t(bX[cluster.1,]),bX[cluster.1,])
XtX1=t(XtX1)/2+XtX1/2
Xty1=matrixVectorMultiply(t(bX[cluster.1,]),by[cluster.1])
yty1=sum(by[cluster.1]^2)
fit.susie1=susie_suff_stat(XtX=XtX1,Xty=Xty1,yty=yty1,n=length(cluster.1),L=Lvec[v],max_iter=300,intercept=F,estimate_prior_method="EM")
theta1=coef.susie(fit.susie1)[-1]*(fit.susie1$pip>(pip.thres*max(1/5,cluster.ratio[1])))
if(length(cluster.2)>5){
Rxysum2=biasterm(RxyList=RxyList,cluster.2)
XtX2=matrixMultiply(t(bX[cluster.2,]),bX[cluster.2,])
XtX2=t(XtX2)/2+XtX2/2
yty2=sum(by[cluster.2]^2)
Xty2=matrixVectorMultiply(t(bX[cluster.2,]),by[cluster.2])
fit.susie2=susie_suff_stat(XtX=XtX2,Xty=Xty2,yty=yty2,n=length(cluster.2),L=Lvec[v],max_iter=300,intercept=F,estimate_prior_method="EM")
theta2=coef.susie(fit.susie2)[-1]*(fit.susie2$pip>(pip.thres*min(1/5,cluster.ratio[2])))
}else{
theta2=theta1*0
}
indtheta1=which(theta1!=0)
if(length(indtheta1)==1){
xtx1=XtX1[indtheta1,indtheta1]-Rxysum1[indtheta1,indtheta1]
xty1=Xty1[indtheta1]-Rxysum1[indtheta1,p+1]
theta1[indtheta1]=xty1/xtx1
}
if(length(indtheta1)>1){
XtX1=XtX1[indtheta1,indtheta1]-Rxysum1[indtheta1,indtheta1]
Xty1=Xty1[indtheta1]-Rxysum1[indtheta1,p+1]
theta1[indtheta1]=c(solve(XtX1)%*%Xty1)
}
indtheta2=which(theta2!=0)
if(length(indtheta2)==1){
xtx2=XtX2[indtheta2,indtheta2]-Rxysum2[indtheta2,indtheta2]
xty2=Xty2[indtheta2]-Rxysum2[indtheta2,p+1]
theta2[indtheta2]=xty2/xtx2
}
if(length(indtheta2)>1){
XtX2=XtX2[indtheta2,indtheta2]-Rxysum2[indtheta2,indtheta2]
Xty2=Xty2[indtheta2]-Rxysum2[indtheta2,p+1]
theta2[indtheta2]=c(solve(XtX2)%*%Xty2)
}
Btheta1[,v]=theta1
Btheta2[,v]=theta2
df1=min(sum(theta1!=0),Lvec[v])
df2=min(sum(theta2!=0),Lvec[v])
Bbic[v]=MRFit(by=by,bX=bX,theta1=theta1,theta2=theta2,cluster.1=cluster.1,cluster.2=cluster.2,df1=df1,df2=df2)+(df2+df1)*(log(p*2)*ebic.theta+log(m))
}
Bbic=Bbic/m
######################## Final Estimate #################################
vstar=which.min(Bbic)
theta1=Btheta1[,vstar]
theta2=Btheta2[,vstar]
XtX1=matrixMultiply(t(bX[cluster.1,]),bX[cluster.1,])
XtX1=t(XtX1)/2+XtX1/2
Xty1=matrixVectorMultiply(t(bX[cluster.1,]),by[cluster.1])
yty1=sum(by[cluster.1]^2)
fit.susie1=susie_suff_stat(XtX=XtX1,Xty=Xty1,yty=yty1,n=length(cluster.1),L=Lvec[vstar],max_iter=300,intercept=F,estimate_prior_method="EM")
theta1=coef.susie(fit.susie1)[-1]*(fit.susie1$pip>(pip.thres*max(1/5,cluster.ratio[1])))
if(length(cluster.2)>5){
XtX2=matrixMultiply(t(bX[cluster.2,]),bX[cluster.2,])
XtX2=t(XtX2)/2+XtX2/2
Xty2=matrixVectorMultiply(t(bX[cluster.2,]),by[cluster.2])
yty2=sum(by[cluster.2]^2)
fit.susie2=susie_suff_stat(XtX=XtX2,Xty=Xty2,yty=yty2,n=length(cluster.2),L=Lvec[vstar],max_iter=300,intercept=F,estimate_prior_method="EM")
theta2=coef.susie(fit.susie2)[-1]*(fit.susie2$pip>(pip.thres*min(1/5,cluster.ratio[2])))
}else{
theta2=theta1*0
}
indtheta1=which(theta1!=0)
if(length(indtheta1)==1){
xtx1=XtX1[indtheta1,indtheta1]-Rxysum1[indtheta1,indtheta1]
xty1=Xty1[indtheta1]-Rxysum1[indtheta1,p+1]
theta1[indtheta1]=xty1/xtx1
}
if(length(indtheta1)>1){
XtX1=XtX1[indtheta1,indtheta1]-Rxysum1[indtheta1,indtheta1]
Xty1=Xty1[indtheta1]-Rxysum1[indtheta1,p+1]
theta1[indtheta1]=c(solve(XtX1)%*%Xty1)
}
indtheta2=which(theta2!=0)
if(length(indtheta2)==1){
xtx2=XtX2[indtheta2,indtheta2]-Rxysum2[indtheta2,indtheta2]
xty2=Xty2[indtheta2]-Rxysum2[indtheta2,p+1]
theta2[indtheta2]=xty2/xtx2
}
if(length(indtheta2)>1){
XtX2=XtX2[indtheta2,indtheta2]-Rxysum2[indtheta2,indtheta2]
Xty2=Xty2[indtheta2]-Rxysum2[indtheta2,p+1]
theta2[indtheta2]=c(solve(XtX2)%*%Xty2)
}
############################### inference #########################
cat("bootstrapping process ...")
sink(tempfile())
names(theta1)=names(theta2)=colnames(bX)
ThetaList1=ThetaList2=matrix(0,sampling.time,p)
colnames(ThetaList1)=colnames(ThetaList2)=colnames(bX)
for(j in 1:sampling.time) {
indicator <- FALSE
tryCatch({
indj=sample(m,m*0.5,replace=F)
byj=by[indj]
bXj=bX[indj,]
theta1j=theta1
theta2j=theta2
error=1
iter=1
fit.mixturej=regmixEM(y=byj,x=bXj,k=2,addintercept=F,beta=cbind(theta1j,theta2j)*runif(1,0.95,1.05)*0.95,maxit=100,epsilon=1e-3)
max.cluster=ifelse(sum(fit.mixturej$posterior[,1]>main.cluster.thres)>(m/2),1,2)
cluster.1j=which(fit.mixturej$posterior[,max.cluster]>main.cluster.thres)
cluster.2j=which(fit.mixturej$posterior[,max.cluster]<=main.cluster.thres)
Rxysum1j=biasterm(RxyList=RxyList,indj[cluster.1j])
XtX1j=matrixMultiply(t(bXj[cluster.1j,]),bXj[cluster.1j,])
XtX1j=t(XtX1j)/2+XtX1j/2
Xty1j=matrixVectorMultiply(t(bXj[cluster.1j,]),byj[cluster.1j])
yty1j=sum(byj[cluster.1j]^2)
fit.susie1j=susie_suff_stat(XtX=XtX1j,Xty=Xty1j,yty=yty1j,n=length(cluster.1j),L=Lvec[vstar],max_iter=300,intercept=F,estimate_prior_method="EM")
theta1j=coef.susie(fit.susie1j)[-1]*(fit.susie1j$pip>(pip.thres*max(1/5,cluster.ratio[1])))
if(length(cluster.2j)>5){
Rxysum2j=biasterm(RxyList=RxyList,indj[cluster.2j])
Xty2j=matrixVectorMultiply(t(bXj[cluster.2j,]),byj[cluster.2j])
yty2j=sum(byj[cluster.2j]^2)
XtX2j=matrixMultiply(t(bXj[cluster.2j,]),bXj[cluster.2j,])
XtX2j=t(XtX2j)/2+XtX2j/2
fit.susie2j=susie_suff_stat(XtX=XtX2j,Xty=Xty2j,yty=yty2j,n=length(cluster.2j),L=Lvec[vstar],max_iter=300,intercept=F,estimate_prior_method="EM")
theta2j=coef.susie(fit.susie2j)[-1]*(fit.susie2j$pip>(pip.thres*min(1/5,cluster.ratio[2])))
}else{
theta2j=theta1*0
}
indtheta1j=which(theta1j!=0)
if(length(indtheta1j)==1){
xtx1j=XtX1j[indtheta1j,indtheta1j]-Rxysum1j[indtheta1j,indtheta1j]
xty1j=Xty1j[indtheta1j]-Rxysum1j[indtheta1j,p+1]
theta1j[indtheta1j]=xty1j/xtx1j
}
if(length(indtheta1j)>1){
XtX1j=XtX1j[indtheta1j,indtheta1j]-Rxysum1j[indtheta1j,indtheta1j]
Xty1j=Xty1j[indtheta1j]-Rxysum1j[indtheta1j,p+1]
theta1j[indtheta1j]=c(solve(XtX1j)%*%Xty1j)
}
indtheta2j=which(theta2j!=0)
if(length(indtheta2j)==1){
xtx2j=XtX2j[indtheta2j,indtheta2j]-Rxysum2j[indtheta2j,indtheta2j]
xty2j=Xty2j[indtheta2j]-Rxysum2j[indtheta2j,p+1]
theta2j[indtheta2j]=xty2j/xtx2j
}
if(length(indtheta2j)>1){
XtX2j=XtX2j[indtheta2j,indtheta2j]-Rxysum2j[indtheta2j,indtheta2j]
Xty2j=Xty2j[indtheta2j]-Rxysum2j[indtheta2j,p+1]
theta2j[indtheta2j]=c(solve(XtX2j)%*%Xty2j)
}
ThetaVecj=cbind(theta1j,theta2j)
ThetaNormj=colMeans((ThetaVecj-cbind(theta1,theta1))^2)
theta1j=ThetaVecj[,which.min(ThetaNormj)]
theta2j=ThetaVecj[,which.max(ThetaNormj)]

ThetaList1[j, ] <- theta1j
ThetaList2[j, ] <- theta2j
}, error = function(e) {
# Error handling block
cat("Error occurred: ", e$message, "\n")
indicator <<- TRUE  # Set indicator to TRUE if an error occurs
j <<- j - 1  # Decrement the iteration counter to retry
})
if (indicator) {
next  # Retry the current iteration
}
}
indtheta1=which(theta1!=0)
indtheta2=which(theta2!=0)
theta.se1=colSD(ThetaList1)
theta.cov1=cov(ThetaList1)
theta.se2=colSD(ThetaList2)
theta.cov2=cov(ThetaList2)
if(robust.se==T){
theta.se1=colSDMAD(ThetaList1)
theta.cov1=covmad(ThetaList1)
theta.se2=colSDMAD(ThetaList2)
theta.cov2=covmad(ThetaList2)
}
colnames(theta.cov2)=rownames(theta.cov2)=names(theta.se2)=colnames(bX)
colnames(theta.cov1)=rownames(theta.cov1)=names(theta.se1)=colnames(bX)
A=list()
A$theta1=theta1
A$theta2=theta2
A$theta.se1=theta.se1
A$theta.cov1=theta.cov1
A$theta.se2=theta.se2
A$theta.cov2=theta.cov2
A$Bic=Bbic
A$reliability.adjust=r
A$thetalist2=ThetaList2
A$thetalist1=ThetaList1
A$cluster1=cluster.1
A$cluster2=cluster.2
A$theta.pip1=colMeans(ThetaList1!=0)
A$theta.pip2=colMeans(ThetaList2!=0)
A$fit.mixture=fit.mixture
A$theta.pratt1=getPratt(bX=bX[cluster.1,],by=by[cluster.1],bXse=bXse[cluster.1,],byse=byse[cluster.1],theta=theta1,Rxy=Rxy)
A$theta.pratt2=getPratt(bX=bX[cluster.2,],by=by[cluster.2],bXse=bXse[cluster.2,],byse=byse[cluster.2],theta=theta2,Rxy=Rxy)
A$IsIPOD=F
sink()
return(A)
}else{
A$IsIPOD=T
return(A)
}
}
