# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

construct_sparse_blockwise_LD_cpp <- function(LD, cluster_index, cluster_sampling, admm_rho) {
    .Call(`_MRBEEX_construct_sparse_blockwise_LD_cpp`, LD, cluster_index, cluster_sampling, admm_rho)
}

get_matrix_info_cpp <- function(mat) {
    .Call(`_MRBEEX_get_matrix_info_cpp`, mat)
}

